// <auto-generated />
using System;
using DonzoApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonzoApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("DonzoApp.API.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("DonzoApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DonzoApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("DonzoApp.API.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MoodIdId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserIdId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WTypeIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MoodIdId");

                    b.HasIndex("UserIdId");

                    b.HasIndex("WTypeIdId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("DonzoApp.API.Models.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutType");
                });

            modelBuilder.Entity("DonzoApp.API.Models.Workout", b =>
                {
                    b.HasOne("DonzoApp.API.Models.Mood", "MoodId")
                        .WithMany()
                        .HasForeignKey("MoodIdId");

                    b.HasOne("DonzoApp.API.Models.User", "UserId")
                        .WithMany("Workouts")
                        .HasForeignKey("UserIdId");

                    b.HasOne("DonzoApp.API.Models.WorkoutType", "WTypeId")
                        .WithMany()
                        .HasForeignKey("WTypeIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
